### ISSUE TITLE
Design + implement view forms list view page

### ISSUE THREAD

**Issue by jackielincroft** [Code-4-Community/constellation#14]
It might be helpful do some sort of designing/planning around this before getting straight into it (low fi wireframes, sketches, or just some quick notes/description)

No hard requirements about what this page should show, but the goal is for Lori and team to be able to see past forms submitted

I think a list of cards (https://chakra-ui.com/docs/components/card/usage) or a table (https://chakra-ui.com/docs/components/table/usage) with clickable items could work well, but its totally up to the designer to make whatever they want that has good UX!

**Comment by jennya-alexeyeva** [comment]
![Untitled](https://user-images.githubusercontent.com/40237795/221433503-ffba2c86-8fec-4b58-90ed-1e0f73d1d8ea.png)
